### ISSUE TITLE
Problem loading images when scrolling slow

### ISSUE THREAD

**Issue by gafrancischini** [maurycyw/StaggeredGridView#27] opened 2013-04-26 01:59 UTC
When scrolling the gridview slowly some images doesn't load correctly.

When scrolling fast and then stops scrolling everything seems fine.

**Comment by briangriffey** [comment] 2013-11-03 22:14
Without a specific example I can not reproduce.

**Comment by briangriffey** [comment] 2013-12-02 15:01
@gafrancischini My guess is that your ImageViews haven't gotten a size yet because the the image hasn't loaded yet.  I'm going to close this issue unless you can give me something with specific code to reproduce the issue.

**Closed as completed by briangriffey** 2013-12-02 15:01 UTC
