### ISSUE TITLE
Binary XML file line #9 error

### ISSUE THREAD

**Issue by bkothari99** [maurycyw/StaggeredGridView#21] opened 2013-04-02 13:21 UTC
I try it many times but it give me errors...

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.staggeredgridviewdemo/com.example.staggeredgridviewdemo.MainActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class com.origamilabs.library.views.StaggeredGridView

Can you Please send me 1  full source code example with library ?
If possible then Please mail me:bkothari99@gmail.com

**Comment by maurycyw** [comment] 2013-04-05 21:11
could you provide the full stacktrace?

**Comment by appie21** [comment] 2013-09-19 04:32
hi, i faced the same problem.
here is the full stack trace........

09-19 00:25:56.883: E/AndroidRuntime(803): FATAL EXCEPTION: main
09-19 00:25:56.883: E/AndroidRuntime(803): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.org.digiinno/com.org.digiinno.MyStaggeredViewActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class com.origamilabs.library.views.StaggeredGridView
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.app.ActivityThread.access$600(ActivityThread.java:141)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.os.Handler.dispatchMessage(Handler.java:99)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.os.Looper.loop(Looper.java:137)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.app.ActivityThread.main(ActivityThread.java:5103)
09-19 00:25:56.883: E/AndroidRuntime(803):  at java.lang.reflect.Method.invokeNative(Native Method)
09-19 00:25:56.883: E/AndroidRuntime(803):  at java.lang.reflect.Method.invoke(Method.java:525)
09-19 00:25:56.883: E/AndroidRuntime(803):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
09-19 00:25:56.883: E/AndroidRuntime(803):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
09-19 00:25:56.883: E/AndroidRuntime(803):  at dalvik.system.NativeStart.main(Native Method)
09-19 00:25:56.883: E/AndroidRuntime(803): Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.origamilabs.library.views.StaggeredGridView
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.view.LayoutInflater.createView(LayoutInflater.java:620)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
09-19 00:25:56.883: E/AndroidRuntime(803):  at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:267)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.app.Activity.setContentView(Activity.java:1895)
09-19 00:25:56.883: E/AndroidRuntime(803):  at com.org.digiinno.MyStaggeredViewActivity.onCreate(MyStaggeredViewActivity.java:18)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.app.Activity.performCreate(Activity.java:5133)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
09-19 00:25:56.883: E/AndroidRuntime(803):  ... 11 more
09-19 00:25:56.883: E/AndroidRuntime(803): Caused by: java.lang.reflect.InvocationTargetException
09-19 00:25:56.883: E/AndroidRuntime(803):  at java.lang.reflect.Constructor.constructNative(Native Method)
09-19 00:25:56.883: E/AndroidRuntime(803):  at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
09-19 00:25:56.883: E/AndroidRuntime(803):  at android.view.LayoutInflater.createView(LayoutInflater.java:594)
09-19 00:25:56.883: E/AndroidRuntime(803):  ... 22 more
09-19 00:25:56.883: E/AndroidRuntime(803): Caused by: java.lang.NoClassDefFoundError: android.support.v4.util.SparseArrayCompat
09-19 00:25:56.883: E/AndroidRuntime(803):  at com.origamilabs.library.views.StaggeredGridView.<init>(StaggeredGridView.java:297)
09-19 00:25:56.883: E/AndroidRuntime(803):  at com.origamilabs.library.views.StaggeredGridView.<init>(StaggeredGridView.java:304)
09-19 00:25:56.883: E/AndroidRuntime(803):  ... 25 more

**Comment by briangriffey** [comment] 2013-10-18 01:16
This is not an issue with this project. Closing

**Closed as completed by briangriffey** 2013-10-18 01:16 UTC
